# Cityperks-Frontend
# Dockerfile for cityperks-fe development environment

FROM node:20-alpine AS dev-builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
