export enum RequestStatusEnum {
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  APPROVED = "APPROVED",
}

export enum RequestTypeEnum {
  MERCHANT_UPDATE_REQUEST = "MERCHANT_UPDATE_REQUEST",
  MERCHANT_REGISTRATION_REQUEST = "MERCHANT_REGISTRATION_REQUEST",
}
